export const HARDINESS_ZONES = [
  { zone: "1a", temp: "Below -60°F", description: "Extremely cold, Arctic conditions" },
  { zone: "1b", temp: "-55 to -60°F", description: "Extremely cold, Arctic conditions" },
  { zone: "2a", temp: "-50 to -55°F", description: "Very cold, subarctic conditions" },
  { zone: "2b", temp: "-45 to -50°F", description: "Very cold, subarctic conditions" },
  { zone: "3a", temp: "-40 to -45°F", description: "Cold winters, short growing season" },
  { zone: "3b", temp: "-35 to -40°F", description: "Cold winters, short growing season" },
  { zone: "4a", temp: "-30 to -35°F", description: "Cold winters, moderate growing season" },
  { zone: "4b", temp: "-25 to -30°F", description: "Cold winters, moderate growing season" },
  { zone: "5a", temp: "-20 to -25°F", description: "Cold winters, good growing season" },
  { zone: "5b", temp: "-15 to -20°F", description: "Cold winters, good growing season" },
  { zone: "6a", temp: "-10 to -15°F", description: "Moderate climate, versatile planting" },
  { zone: "6b", temp: "-5 to -10°F", description: "Moderate climate, versatile planting" },
  { zone: "7a", temp: "0 to -5°F", description: "Mild winters, long growing season" },
  { zone: "7b", temp: "5 to 0°F", description: "Mild winters, long growing season" },
  { zone: "8a", temp: "10 to 5°F", description: "Mild climate, extended growing season" },
  { zone: "8b", temp: "15 to 10°F", description: "Mild climate, extended growing season" },
  { zone: "9a", temp: "20 to 15°F", description: "Warm climate, year-round gardening" },
  { zone: "9b", temp: "25 to 20°F", description: "Warm climate, year-round gardening" },
  { zone: "10a", temp: "30 to 25°F", description: "Tropical/subtropical climate" },
  { zone: "10b", temp: "35 to 30°F", description: "Tropical/subtropical climate" },
  { zone: "11a", temp: "40 to 35°F", description: "Tropical climate, no frost" },
  { zone: "11b", temp: "Above 40°F", description: "Tropical climate, no frost" },
]
