export interface Plant {
  id: string
  name: string
  scientificName: string
  type: "edible" | "ornamental"
  zones: number[]
  seasons: ("spring" | "summer" | "fall" | "winter" | "year-round")[]
  isSunNative: boolean
  sunRequirement: "full-sun" | "partial-shade" | "full-shade"
  waterNeeds: "low" | "medium" | "high"
  difficulty: "easy" | "medium" | "hard"
  companions: string[]
  description: string
  imageQuery: string
}

export const MOCK_PLANTS: Plant[] = [
  {
    id: "1",
    name: "Tomato",
    scientificName: "Solanum lycopersicum",
    type: "edible",
    zones: [3, 4, 5, 6, 7, 8, 9, 10, 11],
    seasons: ["spring", "summer"],
    isSunNative: true,
    sunRequirement: "full-sun",
    waterNeeds: "medium",
    difficulty: "easy",
    companions: ["basil", "marigold", "carrot", "parsley"],
    description: "Popular garden vegetable with juicy fruits. Best grown in warm weather with plenty of sunlight.",
    imageQuery: "red tomatoes on vine garden",
  },
  {
    id: "2",
    name: "Basil",
    scientificName: "Ocimum basilicum",
    type: "edible",
    zones: [4, 5, 6, 7, 8, 9, 10],
    seasons: ["spring", "summer"],
    isSunNative: true,
    sunRequirement: "full-sun",
    waterNeeds: "medium",
    difficulty: "easy",
    companions: ["tomato", "pepper"],
    description: "Aromatic herb perfect for cooking. Grows well alongside tomatoes and repels pests.",
    imageQuery: "fresh basil leaves garden",
  },
  {
    id: "3",
    name: "Carrot",
    scientificName: "Daucus carota",
    type: "edible",
    zones: [3, 4, 5, 6, 7, 8, 9],
    seasons: ["spring", "fall"],
    isSunNative: false,
    sunRequirement: "full-sun",
    waterNeeds: "medium",
    difficulty: "medium",
    companions: ["tomato", "lettuce", "onion"],
    description: "Root vegetable that thrives in loose, well-drained soil. Great for succession planting.",
    imageQuery: "orange carrots growing soil",
  },
  {
    id: "4",
    name: "Lettuce",
    scientificName: "Lactuca sativa",
    type: "edible",
    zones: [2, 3, 4, 5, 6, 7, 8, 9, 10],
    seasons: ["spring", "fall"],
    isSunNative: false,
    sunRequirement: "partial-shade",
    waterNeeds: "medium",
    difficulty: "easy",
    companions: ["carrot", "radish", "beet"],
    description: "Cool-season leafy green. Perfect for salads and grows quickly in spring and fall.",
    imageQuery: "green lettuce leaves garden bed",
  },
  {
    id: "5",
    name: "Spinach",
    scientificName: "Spinacia oleracea",
    type: "edible",
    zones: [2, 3, 4, 5, 6, 7, 8, 9],
    seasons: ["spring", "fall"],
    isSunNative: false,
    sunRequirement: "partial-shade",
    waterNeeds: "medium",
    difficulty: "easy",
    companions: ["strawberry", "pea", "bean"],
    description: "Nutrient-rich leafy green that prefers cooler temperatures. Excellent for spring and fall gardens.",
    imageQuery: "fresh spinach leaves growing",
  },
  {
    id: "6",
    name: "Blueberry",
    scientificName: "Vaccinium corymbosum",
    type: "edible",
    zones: [3, 4, 5, 6, 7, 8],
    seasons: ["spring", "summer"],
    isSunNative: true,
    sunRequirement: "full-sun",
    waterNeeds: "medium",
    difficulty: "medium",
    companions: ["strawberry", "thyme"],
    description: "Perennial berry bush that produces sweet fruits. Requires acidic soil.",
    imageQuery: "blueberries on bush garden",
  },
  {
    id: "7",
    name: "Raspberry",
    scientificName: "Rubus idaeus",
    type: "edible",
    zones: [3, 4, 5, 6, 7, 8],
    seasons: ["summer", "fall"],
    isSunNative: true,
    sunRequirement: "full-sun",
    waterNeeds: "medium",
    difficulty: "medium",
    companions: ["garlic", "chives"],
    description: "Cane fruit that produces delicious berries. Spreads via runners.",
    imageQuery: "red raspberries on canes",
  },
  {
    id: "8",
    name: "Strawberry",
    scientificName: "Fragaria × ananassa",
    type: "edible",
    zones: [3, 4, 5, 6, 7, 8, 9],
    seasons: ["spring", "summer"],
    isSunNative: true,
    sunRequirement: "full-sun",
    waterNeeds: "medium",
    difficulty: "easy",
    companions: ["spinach", "blueberry", "thyme"],
    description: "Low-growing perennial that produces sweet fruits. Great for ground cover.",
    imageQuery: "strawberries growing garden plants",
  },
  {
    id: "9",
    name: "Rose",
    scientificName: "Rosa spp.",
    type: "ornamental",
    zones: [3, 4, 5, 6, 7, 8, 9, 10],
    seasons: ["spring", "summer", "fall"],
    isSunNative: true,
    sunRequirement: "full-sun",
    waterNeeds: "medium",
    difficulty: "medium",
    companions: ["lavender", "catmint", "geranium"],
    description: "Classic flowering shrub with fragrant blooms. Requires regular pruning.",
    imageQuery: "pink roses blooming garden",
  },
  {
    id: "10",
    name: "Lavender",
    scientificName: "Lavandula angustifolia",
    type: "ornamental",
    zones: [5, 6, 7, 8, 9],
    seasons: ["spring", "summer"],
    isSunNative: true,
    sunRequirement: "full-sun",
    waterNeeds: "low",
    difficulty: "easy",
    companions: ["rose", "sage", "thyme"],
    description: "Aromatic perennial with purple flowers. Drought-tolerant and attracts pollinators.",
    imageQuery: "purple lavender flowers field",
  },
  {
    id: "11",
    name: "Sunflower",
    scientificName: "Helianthus annuus",
    type: "ornamental",
    zones: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    seasons: ["summer", "fall"],
    isSunNative: true,
    sunRequirement: "full-sun",
    waterNeeds: "medium",
    difficulty: "easy",
    companions: ["cucumber", "corn", "squash"],
    description: "Tall annual with large, cheerful blooms. Produces edible seeds.",
    imageQuery: "yellow sunflowers blooming tall",
  },
  {
    id: "12",
    name: "Marigold",
    scientificName: "Tagetes spp.",
    type: "ornamental",
    zones: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    seasons: ["spring", "summer", "fall"],
    isSunNative: true,
    sunRequirement: "full-sun",
    waterNeeds: "low",
    difficulty: "easy",
    companions: ["tomato", "cucumber", "squash"],
    description: "Bright annual flower that repels pests. Perfect companion plant for vegetables.",
    imageQuery: "orange marigold flowers garden",
  },
  {
    id: "13",
    name: "Zinnia",
    scientificName: "Zinnia elegans",
    type: "ornamental",
    zones: [3, 4, 5, 6, 7, 8, 9, 10],
    seasons: ["summer", "fall"],
    isSunNative: true,
    sunRequirement: "full-sun",
    waterNeeds: "medium",
    difficulty: "easy",
    companions: ["cucumber", "bean", "tomato"],
    description: "Colorful annual that attracts butterflies. Long-lasting cut flowers.",
    imageQuery: "colorful zinnia flowers blooming",
  },
  {
    id: "14",
    name: "Daylily",
    scientificName: "Hemerocallis spp.",
    type: "ornamental",
    zones: [3, 4, 5, 6, 7, 8, 9],
    seasons: ["spring", "summer"],
    isSunNative: true,
    sunRequirement: "full-sun",
    waterNeeds: "medium",
    difficulty: "easy",
    companions: ["hosta", "coneflower", "black-eyed susan"],
    description: "Hardy perennial with trumpet-shaped flowers. Each bloom lasts one day.",
    imageQuery: "orange daylily flowers garden",
  },
  {
    id: "15",
    name: "Coneflower",
    scientificName: "Echinacea purpurea",
    type: "ornamental",
    zones: [3, 4, 5, 6, 7, 8, 9],
    seasons: ["summer", "fall"],
    isSunNative: true,
    sunRequirement: "full-sun",
    waterNeeds: "medium",
    difficulty: "easy",
    companions: ["black-eyed susan", "bee balm", "salvia"],
    description: "Native perennial with distinctive cone-shaped centers. Attracts butterflies and bees.",
    imageQuery: "purple coneflower echinacea garden",
  },
  {
    id: "16",
    name: "Pepper",
    scientificName: "Capsicum annuum",
    type: "edible",
    zones: [3, 4, 5, 6, 7, 8, 9, 10, 11],
    seasons: ["spring", "summer"],
    isSunNative: true,
    sunRequirement: "full-sun",
    waterNeeds: "medium",
    difficulty: "medium",
    companions: ["basil", "onion", "spinach"],
    description: "Warm-season vegetable with sweet or spicy fruits. Needs consistent watering.",
    imageQuery: "bell peppers growing plants",
  },
  {
    id: "17",
    name: "Cucumber",
    scientificName: "Cucumis sativus",
    type: "edible",
    zones: [3, 4, 5, 6, 7, 8, 9, 10],
    seasons: ["summer"],
    isSunNative: true,
    sunRequirement: "full-sun",
    waterNeeds: "high",
    difficulty: "easy",
    companions: ["bean", "pea", "radish", "sunflower"],
    description: "Vining vegetable that produces refreshing fruits. Great for pickling.",
    imageQuery: "cucumbers growing on vine",
  },
  {
    id: "18",
    name: "Bean",
    scientificName: "Phaseolus vulgaris",
    type: "edible",
    zones: [3, 4, 5, 6, 7, 8, 9, 10],
    seasons: ["spring", "summer"],
    isSunNative: true,
    sunRequirement: "full-sun",
    waterNeeds: "medium",
    difficulty: "easy",
    companions: ["corn", "cucumber", "carrot"],
    description: "Nitrogen-fixing legume. Available in bush and pole varieties.",
    imageQuery: "green beans growing garden",
  },
  {
    id: "19",
    name: "Kale",
    scientificName: "Brassica oleracea",
    type: "edible",
    zones: [2, 3, 4, 5, 6, 7, 8, 9],
    seasons: ["spring", "fall", "winter"],
    isSunNative: false,
    sunRequirement: "full-sun",
    waterNeeds: "medium",
    difficulty: "easy",
    companions: ["onion", "beet", "celery"],
    description: "Cold-hardy leafy green rich in nutrients. Frost actually improves flavor.",
    imageQuery: "curly kale leaves growing",
  },
  {
    id: "20",
    name: "Radish",
    scientificName: "Raphanus sativus",
    type: "edible",
    zones: [2, 3, 4, 5, 6, 7, 8, 9, 10],
    seasons: ["spring", "fall"],
    isSunNative: false,
    sunRequirement: "full-sun",
    waterNeeds: "medium",
    difficulty: "easy",
    companions: ["lettuce", "pea", "cucumber"],
    description: "Fast-growing root vegetable. Ready to harvest in just 3-4 weeks.",
    imageQuery: "red radishes growing soil",
  },
  {
    id: "21",
    name: "Pumpkin",
    scientificName: "Cucurbita pepo",
    type: "edible",
    zones: [3, 4, 5, 6, 7, 8, 9, 10],
    seasons: ["summer", "fall"],
    isSunNative: true,
    sunRequirement: "full-sun",
    waterNeeds: "high",
    difficulty: "medium",
    companions: ["corn", "bean", "marigold"],
    description: "Vining squash that needs plenty of space. Perfect for fall harvest.",
    imageQuery: "orange pumpkins growing vine",
  },
  {
    id: "22",
    name: "Sage",
    scientificName: "Salvia officinalis",
    type: "edible",
    zones: [4, 5, 6, 7, 8, 9],
    seasons: ["year-round"],
    isSunNative: true,
    sunRequirement: "full-sun",
    waterNeeds: "low",
    difficulty: "easy",
    companions: ["rosemary", "cabbage", "carrot"],
    description: "Perennial herb with aromatic leaves. Drought-tolerant once established.",
    imageQuery: "sage plant purple flowers",
  },
  {
    id: "23",
    name: "Thyme",
    scientificName: "Thymus vulgaris",
    type: "edible",
    zones: [5, 6, 7, 8, 9],
    seasons: ["year-round"],
    isSunNative: true,
    sunRequirement: "full-sun",
    waterNeeds: "low",
    difficulty: "easy",
    companions: ["strawberry", "lavender", "cabbage"],
    description: "Low-growing perennial herb. Excellent ground cover and culinary herb.",
    imageQuery: "thyme herb garden growing",
  },
  {
    id: "24",
    name: "Parsley",
    scientificName: "Petroselinum crispum",
    type: "edible",
    zones: [5, 6, 7, 8, 9],
    seasons: ["spring", "summer", "fall"],
    isSunNative: false,
    sunRequirement: "partial-shade",
    waterNeeds: "medium",
    difficulty: "easy",
    companions: ["tomato", "asparagus", "corn"],
    description: "Biennial herb with fresh, bright flavor. Attracts beneficial insects.",
    imageQuery: "fresh parsley leaves garden",
  },
  {
    id: "25",
    name: "Mint",
    scientificName: "Mentha spp.",
    type: "edible",
    zones: [3, 4, 5, 6, 7, 8, 9],
    seasons: ["spring", "summer", "fall"],
    isSunNative: false,
    sunRequirement: "partial-shade",
    waterNeeds: "high",
    difficulty: "easy",
    companions: ["cabbage", "tomato"],
    description: "Aromatic herb that spreads aggressively. Best grown in containers.",
    imageQuery: "mint leaves growing fresh",
  },
  {
    id: "26",
    name: "Black-eyed Susan",
    scientificName: "Rudbeckia hirta",
    type: "ornamental",
    zones: [3, 4, 5, 6, 7, 8, 9],
    seasons: ["summer", "fall"],
    isSunNative: true,
    sunRequirement: "full-sun",
    waterNeeds: "medium",
    difficulty: "easy",
    companions: ["coneflower", "salvia", "aster"],
    description: "Native perennial with cheerful yellow blooms. Very low maintenance.",
    imageQuery: "black eyed susan yellow flowers",
  },
  {
    id: "27",
    name: "Bee Balm",
    scientificName: "Monarda didyma",
    type: "ornamental",
    zones: [4, 5, 6, 7, 8, 9],
    seasons: ["summer"],
    isSunNative: true,
    sunRequirement: "full-sun",
    waterNeeds: "medium",
    difficulty: "easy",
    companions: ["tomato", "coneflower", "phlox"],
    description: "Native perennial that attracts hummingbirds and bees. Fragrant flowers.",
    imageQuery: "red bee balm flowers garden",
  },
  {
    id: "28",
    name: "Hosta",
    scientificName: "Hosta spp.",
    type: "ornamental",
    zones: [3, 4, 5, 6, 7, 8, 9],
    seasons: ["spring", "summer"],
    isSunNative: false,
    sunRequirement: "partial-shade",
    waterNeeds: "medium",
    difficulty: "easy",
    companions: ["fern", "astilbe", "daylily"],
    description: "Shade-loving perennial with attractive foliage. Many varieties available.",
    imageQuery: "hosta leaves shade garden",
  },
  {
    id: "29",
    name: "Peony",
    scientificName: "Paeonia spp.",
    type: "ornamental",
    zones: [3, 4, 5, 6, 7, 8],
    seasons: ["spring"],
    isSunNative: true,
    sunRequirement: "full-sun",
    waterNeeds: "medium",
    difficulty: "medium",
    companions: ["rose", "iris", "allium"],
    description: "Long-lived perennial with spectacular blooms. Requires cold winter dormancy.",
    imageQuery: "pink peony flowers blooming",
  },
  {
    id: "30",
    name: "Hydrangea",
    scientificName: "Hydrangea macrophylla",
    type: "ornamental",
    zones: [5, 6, 7, 8, 9],
    seasons: ["summer", "fall"],
    isSunNative: false,
    sunRequirement: "partial-shade",
    waterNeeds: "high",
    difficulty: "medium",
    companions: ["hosta", "fern", "astilbe"],
    description: "Flowering shrub with large blooms. Flower color changes with soil pH.",
    imageQuery: "blue hydrangea flowers blooming",
  },
]

export const HARDINESS_ZONES = [
  { zone: "1a", temp: "Below -60°F", description: "Extremely cold, Arctic conditions" },
  { zone: "1b", temp: "-55 to -60°F", description: "Extremely cold, Arctic conditions" },
  { zone: "2a", temp: "-50 to -55°F", description: "Very cold, subarctic conditions" },
  { zone: "2b", temp: "-45 to -50°F", description: "Very cold, subarctic conditions" },
  { zone: "3a", temp: "-40 to -45°F", description: "Cold winters, short growing season" },
  { zone: "3b", temp: "-35 to -40°F", description: "Cold winters, short growing season" },
  { zone: "4a", temp: "-30 to -35°F", description: "Cold winters, moderate growing season" },
  { zone: "4b", temp: "-25 to -30°F", description: "Cold winters, moderate growing season" },
  { zone: "5a", temp: "-20 to -25°F", description: "Cold winters, good growing season" },
  { zone: "5b", temp: "-15 to -20°F", description: "Cold winters, good growing season" },
  { zone: "6a", temp: "-10 to -15°F", description: "Moderate climate, versatile planting" },
  { zone: "6b", temp: "-5 to -10°F", description: "Moderate climate, versatile planting" },
  { zone: "7a", temp: "0 to -5°F", description: "Mild winters, long growing season" },
  { zone: "7b", temp: "5 to 0°F", description: "Mild winters, long growing season" },
  { zone: "8a", temp: "10 to 5°F", description: "Mild climate, extended growing season" },
  { zone: "8b", temp: "15 to 10°F", description: "Mild climate, extended growing season" },
  { zone: "9a", temp: "20 to 15°F", description: "Warm climate, year-round gardening" },
  { zone: "9b", temp: "25 to 20°F", description: "Warm climate, year-round gardening" },
  { zone: "10a", temp: "30 to 25°F", description: "Tropical/subtropical climate" },
  { zone: "10b", temp: "35 to 30°F", description: "Tropical/subtropical climate" },
  { zone: "11a", temp: "40 to 35°F", description: "Tropical climate, no frost" },
  { zone: "11b", temp: "Above 40°F", description: "Tropical climate, no frost" },
]
